/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-20 06:48:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Upload_005fProduct;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import semiProject.uploadProduct.ProductDBBean;
import semiProject.uploadProduct.ProductBean;

public final class updateProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("semiProject.uploadProduct.ProductBean");
    _jspx_imports_classes.add("semiProject.uploadProduct.ProductDBBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");

	String pageNum = request.getParameter("pageNum");
	int product_number = Integer.parseInt(request.getParameter("product_number"));
	ProductDBBean updb = ProductDBBean.getInstance();
	ProductBean upbd = updb.getproduct(product_number, false);
	
	System.out.println("넘버어어어어어어어어어어어어"+product_number);
	

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script language=\"JavaScript\" src=\"uploadProduct.js\" charset=\"utf-8\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<center>\n");
      out.write("		<form name=\"up_prodc\" method=\"post\"\n");
      out.write("			 action=\"updateProduct_ok.jsp?product_number=");
      out.print(product_number );
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("\">\n");
      out.write("			<table>\n");
      out.write("				<tr class=\"product_img\">\n");
      out.write("					<td>상품 이미지 등록</td>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"file\" name=\"product_img\">\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr class=\"product_category\">\n");
      out.write("					<td>\n");
      out.write("						<label class=\"dress_label\">옷 카테고리</label>\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<select name=\"category_code\">\n");
      out.write("						    <option value=\"none\">=== 선택 ===</option>\n");
      out.write("						    <option value=\"t-shirt\">티셔츠</option>\n");
      out.write("						    <option value=\"hude-t\">후드티</option>\n");
      out.write("						    <option value=\"nite\">니트/스웨터</option>\n");
      out.write("						    <option value=\"shirt\">셔츠/남방</option>\n");
      out.write("						    <option value=\"pants\">바지</option>\n");
      out.write("						    <option value=\"blue-jeans\">청바지</option>\n");
      out.write("						 </select>\n");
      out.write("					 </td>\n");
      out.write("				</tr>\n");
      out.write("				<br>\n");
      out.write("				<tr class=\"product_name\">\n");
      out.write("					<td>\n");
      out.write("						<label class=\"product_name_label\">상품 이름 </label>&nbsp;\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"text\" name=\"product_name\" value=\"");
      out.print(upbd.getProduct_name());
      out.write("\">\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<br>\n");
      out.write("				<tr class=\"product_price\">\n");
      out.write("					<td>\n");
      out.write("						<label class=\"product_price_label\">상품 가격</label>&nbsp;\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"number\" name=\"product_price\" value=\"");
      out.print(upbd.getProduct_price() );
      out.write("\"> 원\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<br>\n");
      out.write("				<tr class=\"product_stock\">\n");
      out.write("					<td>\n");
      out.write("						<label class=\"product_stock\">재고 수량</label>&nbsp;\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"number\" name=\"product_stock\" value=\"");
      out.print(upbd.getProduct_stock() );
      out.write("\"> 개 남았습니다.\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<br>\n");
      out.write("				<tr class=\"product_desc\">\n");
      out.write("					<td>\n");
      out.write("						<label class=\"product_desc_label\">상품 설명</label>&nbsp;\n");
      out.write("					</td>\n");
      out.write("					<td>\n");
      out.write("					<textarea rows=\"2\" cols=\"60\" name=\"product_desc\" value=\"");
      out.print(upbd.getProduct_desc() );
      out.write("\"></textarea>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<br>\n");
      out.write("				<tr>\n");
      out.write("					<td>\n");
      out.write("						<input type=\"button\" value=\"상품 등록\" onclick=\"check_ok()\">&nbsp;\n");
      out.write("						<input type=\"reset\" value=\"다시작성\">\n");
      out.write("						<input type=\"button\" value=\"등록한 상품 목록\" \n");
      out.write("						onclick=\"location.href='myUploadProduct_List.jsp?pageNum=");
      out.print( pageNum );
      out.write("\">\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</form>\n");
      out.write("	</center>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
